name: Publish to GitHub Packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore BSInc.Templates.sln

    - name: Build
      run: dotnet build BSInc.Templates.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test BSInc.Templates.sln --no-restore --verbosity normal

    - name: Pack
      if: github.event_name == 'push'
      run: dotnet pack BSInc.Templates.sln --configuration Release --no-restore --output ./artifacts

    - name: Add GitHub Packages source
      if: github.event_name == 'push'
      run: dotnet nuget add source --name github "https://nuget.pkg.github.com/two4suited/index.json" --username two4suited --password ${{ secrets.GITHUB_TOKEN }}
 

    - name: Publish to GitHub Packages
      if: github.event_name == 'push'
      run: dotnet nuget push ./artifacts/*.nupkg --source "github"      